### PR TITLE
fixed some typos

### PR DESCRIPTION
**Pull request by juhoffma**
Running through the labs, I noticed, that there are some
inconsistencies within our naming convention meaning, that the ansible
script deploys projects with the name explore-user00…explore-userXX and
in some outputs we still write explore-XX

### CODE REVIEW

**Comment by marekjelen** [comment]
+1

**Comment by siamaksade** [comment]
Good point but the project names shouldn't be hard-coded. Instead "explore{{USER_SUFFIX}}" should be use so that we can change that through the lab definitions.

**Comment by juhoffma** [comment]
Will change

-- 
Jürgen Hoffmann
Sent with Airmail

**Comment by juhoffma** [comment]
Done. Please review and merge

**Comment by siamaksade** [comment]
👍

**Pull request merged**
