### PR TITLE
For default lab, hide lab list and show module list instead

### PR DESCRIPTION
**Pull request by marekjelen**

### CODE REVIEW

**Comment by jorgemoralespou** [comment]
What does this do?

**Comment by marekjelen** [comment]
When the DEFAULT_LAB is set it does render the lab itself instead of redirecting to the lab subdomain.

**Comment by thoraxe** [comment]
Should this be merged?

**Comment by marekjelen** [comment]
Can be ... @jorgemoralespou wanted to wait after his workshop

**Pull request merged**
